INSERT INTO USERS(USERNAME, PASSWORD) VALUES('user', 'servlet');

INSERT INTO BOOKS(TITLE, AUTHOR, PUBLISHER, PUBLISH_DATE) VALUES ('仮のタイトル1', '仮の著者1', '仮の出版社1', '2024-01-01');
INSERT INTO BOOKS(TITLE, AUTHOR, PUBLISHER, PUBLISH_DATE) VALUES ('仮のタイトル2', '仮の著者2', '仮の出版社2', '2024-01-01');
INSERT INTO BOOKS(TITLE, AUTHOR, PUBLISHER, PUBLISH_DATE) VALUES ('仮のタイトル3', '仮の著者3', '仮の出版社3', '2024-01-01');
INSERT INTO BOOKS(TITLE, AUTHOR, PUBLISHER, PUBLISH_DATE) VALUES ('仮のタイトル4', '仮の著者4', '仮の出版社4', '2024-01-01');
INSERT INTO BOOKS(TITLE, AUTHOR, PUBLISHER, PUBLISH_DATE) VALUES ('仮のタイトル5', '仮の著者5', '仮の出版社5', '2024-01-01');
INSERT INTO BOOKS(TITLE, AUTHOR, PUBLISHER, PUBLISH_DATE) VALUES ('仮のタイトル6', '仮の著者6', '仮の出版社6', '2024-01-01');
INSERT INTO BOOKS(TITLE, AUTHOR, PUBLISHER, PUBLISH_DATE) VALUES ('仮のタイトル7', '仮の著者7', '仮の出版社7', '2024-01-01');
